# Generated by Django 4.2.5 on 2023-12-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Y', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_text', models.CharField(max_length=140)),
                ('tweets', models.ManyToManyField(to='Y.tweet')),
            ],
        ),
    ]
